default_platform(:android)

platform :android do
  desc "Lane for Android Firebase distribution"
  lane :firebase_distribution do
    sh"flutter clean"
    sh"flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:540734805944:android:72177ef946c2f7033fa14d",
      firebase_cli_token: "1//03_w2DQqkMmoOCgYIARAAGAMSNwF-L9IrHf_Qn0DcAyeQrJ1XbD6rYxWVlng-Bjqa9nDjju6AKCehwbL1J-lF5tkSL8QudUb47IA",
      android_artifact_type:"APK",
      android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "paytoplay2.official@gmail.com",
      release_notes: "First FastLane Firebase Distribution"
    )
  end
end
