name: Android Fastlane with Firebase App Distribution Workflow # name is optional

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase: # name is optional
    runs-on: ubuntu-latest # ubuntu OS for android 
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17.0.12 # name is optional
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.12'
        distribution: 'temurin'
    
    - name: Install Flutter # name is optional
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4' 
        channel: stable

    - name: Setup Ruby # name is optional
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4.2"
        bundler-cache: true  # caches gems automatically for more speed
        working-directory: android # path to your android directory
        
    - name: Build and Distribute App # name is optional
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        bundle exec fastlane android firebase_distribution
      working-directory: android